//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "t_sample")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub device: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub created_at: String,
    pub sample: String,
    pub predict: i32,
    pub actual: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
